CREATE TABLE [dbo].[Company]
(
	[Company_id] INT NOT NULL PRIMARY KEY, 
    [Comp_type_id] INT NULL, 
    [Comp_name] VARCHAR(50) NULL, 
    [Comp_othernames] VARCHAR(50) NULL, 
    [comp_phone1] VARCHAR(16) NULL, 
    [Comp_phone2] VARCHAR(16) NULL, 
    [Comp_email] VARCHAR(50) NULL, 
    [Comp_RC] VARCHAR(20) NULL, 
    [Comp_address] TEXT NULL, 
    [Comp_city] VARCHAR(50) NULL, 
    [Cust_state] VARCHAR(50) NULL, 
    [Comp_religion] VARCHAR(50) NULL, 
    [Hotel_id] INT NULL, 
    [Department_id] INT NULL, 
    [Employee_id] INT NULL, 
    [date_created] DATETIME NULL, 
    [created_by] INT NULL, 
    [date_updated] DATETIME NULL, 
    [updated_by] INT NULL, 
    [replication_status] BIT NULL, 
    CONSTRAINT [FK_Company_ToHotel] FOREIGN KEY ([Hotel_id]) REFERENCES [Hotel]([hotel_id]), 
    CONSTRAINT [FK_Company_ToEmployee_department] FOREIGN KEY ([Department_id]) REFERENCES [employee_department]([Emp_dept_id]),
)
