CREATE TABLE [dbo].[Customer]
(
	[Customer_id] INT NOT NULL PRIMARY KEY, 
    [Cust_firstName] VARCHAR(50) NULL, 
    [Cust_lastname] VARCHAR(50) NULL, 
    [Cust_othername] VARCHAR(50) NULL, 
    [Cust_listedname] VARCHAR(50) NULL, 
    [Cust_sex] INT NULL, 
    [Cust_DOB] DATE NULL, 
    [VIP_status_id] INT NULL, 
    [Cust_phone1] VARCHAR(16) NULL, 
    [Cust_phone1_call] INT NULL, 
    [Cust_phone1_sms] INT NULL, 
    [Cust_phone1_whatsapp] INT NULL, 
    [Cust_phone2] VARCHAR(16) NULL, 
    [Cust_email] VARCHAR(50) NULL, 
    [Cust_address] TEXT NULL, 
    [Cust_city] VARCHAR(50) NULL, 
    [Cust_state] VARCHAR(50) NULL, 
    [Cust_country] VARCHAR(50) NULL, 
    [Cust_religion] VARCHAR(50) NULL, 
    [Hotel_id] INT NULL, 
    [Depertment_id] INT NULL, 
    [Employee_id] INT NULL, 
    [date_created] DATETIME NULL, 
    [created_by] INT NULL, 
    [date_updated] DATETIME NULL, 
    [updated_by] INT NULL, 
    [replication_status] BIT NULL, 
    CONSTRAINT [FK_Customer_ToHotel] FOREIGN KEY ([Hotel_id]) REFERENCES [Hotel]([hotel_id]), 
    CONSTRAINT [FK_Customer_ToEmployee_department] FOREIGN KEY ([Depertment_id]) REFERENCES [employee_department]([Emp_dept_id]), 
    CONSTRAINT [FK_Customer_ToEmployee_master] FOREIGN KEY ([Employee_id]) REFERENCES [Employee_master]([employee_id])
)
