CREATE TABLE [dbo].[Room_inspection_log]
(
	[insp_id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [insp_type_id] INT NULL, 
    [insp_date] DATE NULL, 
    [insp_time] VARCHAR(50) NULL, 
    [insp_supervisor] VARCHAR(50) NULL, 
    [insp_room_status] INT NULL DEFAULT 0, 
    [insp_isBedsheet] BIT NULL DEFAULT 0, 
    [insp_isTowel] BIT NULL DEFAULT 0, 
    [insp_isTissue] BIT NULL DEFAULT 0, 
    [insp_isWater] BIT NULL DEFAULT 0, 
    [insp_isCup] BIT NULL DEFAULT 0, 
    [insp_bathroom] BIT NULL DEFAULT 0, 
    [insp_isTV] BIT NULL DEFAULT 0, 
    [insp_rating] INT NULL DEFAULT 0, 
    [update_room_status] INT NULL DEFAULT 0, 
    [date_created] DATETIME NULL, 
    [created_by] VARCHAR(50) NULL, 
    [date_updated] DATETIME NULL, 
    [updated_by] VARCHAR(50) NULL, 
    [replication_status] BIT NULL, 
    [Room] VARCHAR(50) NULL,    
    
)
