CREATE TABLE [dbo].[Room_clean_dtls_log]
(
	[Clean_id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [clean_group_id] INT NULL, 
    [Room_id] INT NULL, 
    [Clean_type_id] INT NULL DEFAULT 1, 
    [Clean_date] NCHAR(10) NULL, 
    [Clean_time] NCHAR(10) NULL, 
    [Clean_supervisor] INT NULL, 
    [Clean_housekeeper] INT NULL, 
    [Clean_room_status] INT NULL DEFAULT 0, 
    [Clean_isBedsheet_qyt] INT NULL DEFAULT 0, 
    [Clean_isTowel_qty] INT NULL DEFAULT 0, 
    [Clean_isTissue_qty] INT NULL DEFAULT 0, 
    [Clean_isWater_qty] INT NULL DEFAULT 0, 
    [Clean_isCup_qty] INT NULL DEFAULT 0, 
    [date_created] DATETIME NULL, 
    [created_by] VARCHAR(50) NULL, 
    [date_updated] DATETIME NULL, 
    [updated_by] VARCHAR(50) NULL, 
    [replication_status] BIT NULL, 
    CONSTRAINT [FK_Room_clean_dtls_log_Room_Clean_GroupId] FOREIGN KEY ([clean_group_id]) REFERENCES [Room_clean_log]([clean_group_id]), 
    CONSTRAINT [FK_Room_clean_dtls_log_ToRoom] FOREIGN KEY ([Room_id]) REFERENCES [Rooms]([Room_id]), 
    CONSTRAINT [FK_Room_clean_dtls_log_ToEmployee_Clean_supervisor] FOREIGN KEY ([Clean_supervisor]) REFERENCES [Employee_master]([employee_id]), 
    CONSTRAINT [FK_Room_clean_dtls_log_ToEmployee_Clean_HouseKeeper] FOREIGN KEY ([Clean_housekeeper]) REFERENCES [Employee_master]([employee_id])
)
